// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  x: __t.f32(),
  y: __t.f32(),
  oreType: __t.u32().name("ore_type"),
  size: __t.f32(),
  hp: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  alive: __t.bool(),
  respawnAt: __t.u64().name("respawn_at"),
  rotSpeed: __t.f32().name("rot_speed"),
});
