// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  angle: __t.f32(),
  ship: __t.string(),
  color: __t.string(),
  personality: __t.string(),
  state: __t.string(),
  hp: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  shield: __t.f32(),
  maxShield: __t.f32().name("max_shield"),
  dead: __t.bool(),
  cargoUsed: __t.u32().name("cargo_used"),
  totalKills: __t.u32().name("total_kills"),
  totalMined: __t.u32().name("total_mined"),
  totalEarned: __t.u32().name("total_earned"),
  stunTimer: __t.f32().name("stun_timer"),
  lastUpdate: __t.u64().name("last_update"),
});
