// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  angle: __t.f32(),
  ship: __t.string(),
  color: __t.string(),
  hp: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  shield: __t.f32(),
  maxShield: __t.f32().name("max_shield"),
  cargoUsed: __t.u32().name("cargo_used"),
  dead: __t.bool(),
  cloaked: __t.bool(),
  bounty: __t.bool(),
  kills: __t.u32(),
  earned: __t.u64(),
  lastUpdate: __t.u64().name("last_update"),
  vx: __t.f32(),
  vy: __t.f32(),
});
