// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.string().name("owner_id"),
  ownerName: __t.string().name("owner_name"),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  dmg: __t.f32(),
  color: __t.string(),
  isPlayer: __t.bool().name("is_player"),
  spawnedAt: __t.u64().name("spawned_at"),
  ttlMs: __t.u32().name("ttl_ms"),
});
