// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sellerId: __t.string().name("seller_id"),
  sellerName: __t.string().name("seller_name"),
  sellerType: __t.string().name("seller_type"),
  amountEarned: __t.u64().name("amount_earned"),
  saleType: __t.string().name("sale_type"),
  x: __t.f32(),
  y: __t.f32(),
  timestamp: __t.u64(),
});
