// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  npcId: __t.u32(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  angle: __t.f32(),
  ship: __t.string(),
  color: __t.string(),
  personality: __t.string(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  totalKills: __t.u32(),
  totalMined: __t.u32(),
  totalEarned: __t.u32(),
};
