// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.string(),
  text: __t.string(),
  timestamp: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const KillEvent = __t.object("KillEvent", {
  id: __t.u64(),
  killer: __t.string(),
  victim: __t.string(),
  timestamp: __t.u64(),
});
export type KillEvent = __Infer<typeof KillEvent>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  id: __t.u64(),
  name: __t.string(),
  credits: __t.u64(),
  kills: __t.u32(),
  mined: __t.u64(),
  ship: __t.string(),
  color: __t.string(),
  timestamp: __t.u64(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  angle: __t.f32(),
  ship: __t.string(),
  color: __t.string(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  cargoUsed: __t.u32(),
  dead: __t.bool(),
  cloaked: __t.bool(),
  bounty: __t.bool(),
  kills: __t.u32(),
  earned: __t.u64(),
  lastUpdate: __t.u64(),
});
export type Player = __Infer<typeof Player>;

