// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.string(),
  text: __t.string(),
  timestamp: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const KillEvent = __t.object("KillEvent", {
  id: __t.u64(),
  killer: __t.string(),
  victim: __t.string(),
  timestamp: __t.u64(),
});
export type KillEvent = __Infer<typeof KillEvent>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  id: __t.u64(),
  name: __t.string(),
  credits: __t.u64(),
  kills: __t.u32(),
  mined: __t.u64(),
  ship: __t.string(),
  color: __t.string(),
  timestamp: __t.u64(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const Npc = __t.object("Npc", {
  id: __t.u32(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  angle: __t.f32(),
  ship: __t.string(),
  color: __t.string(),
  personality: __t.string(),
  state: __t.string(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  dead: __t.bool(),
  cargoUsed: __t.u32(),
  totalKills: __t.u32(),
  totalMined: __t.u32(),
  totalEarned: __t.u32(),
  stunTimer: __t.f32(),
  lastUpdate: __t.u64(),
});
export type Npc = __Infer<typeof Npc>;

export const NpcHost = __t.object("NpcHost", {
  id: __t.u32(),
  hostIdentity: __t.string(),
  claimedAt: __t.u64(),
});
export type NpcHost = __Infer<typeof NpcHost>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  angle: __t.f32(),
  ship: __t.string(),
  color: __t.string(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  cargoUsed: __t.u32(),
  dead: __t.bool(),
  cloaked: __t.bool(),
  bounty: __t.bool(),
  kills: __t.u32(),
  earned: __t.u64(),
  lastUpdate: __t.u64(),
  vx: __t.f32(),
  vy: __t.f32(),
  miningX: __t.f32(),
  miningY: __t.f32(),
  miningOre: __t.string(),
  lastDamageTime: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const Projectile = __t.object("Projectile", {
  id: __t.u64(),
  ownerId: __t.string(),
  ownerName: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  dmg: __t.f32(),
  color: __t.string(),
  isPlayer: __t.bool(),
  spawnedAt: __t.u64(),
  ttlMs: __t.u32(),
});
export type Projectile = __Infer<typeof Projectile>;

export const SpaceStation = __t.object("SpaceStation", {
  id: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  dead: __t.bool(),
  respawnAt: __t.u64(),
  lastUpdate: __t.u64(),
});
export type SpaceStation = __Infer<typeof SpaceStation>;

export const Wingman = __t.object("Wingman", {
  id: __t.string(),
  ownerIdentityHex: __t.string(),
  name: __t.string(),
  ship: __t.string(),
  color: __t.string(),
  wmType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  angle: __t.f32(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  dead: __t.bool(),
  state: __t.string(),
  lastUpdate: __t.u64(),
});
export type Wingman = __Infer<typeof Wingman>;

export const WorldState = __t.object("WorldState", {
  id: __t.u32(),
  worldSeed: __t.u64(),
});
export type WorldState = __Infer<typeof WorldState>;

