// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  ownerIdentityHex: __t.string().name("owner_identity_hex"),
  name: __t.string(),
  ship: __t.string(),
  color: __t.string(),
  wmType: __t.string().name("wm_type"),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  angle: __t.f32(),
  hp: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  shield: __t.f32(),
  maxShield: __t.f32().name("max_shield"),
  dead: __t.bool(),
  state: __t.string(),
  lastUpdate: __t.u64().name("last_update"),
});
