// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClientConnectedReducer from "../client_connected_reducer";
import ClientDisconnectedReducer from "../client_disconnected_reducer";
import JoinGameReducer from "../join_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import PruneEventsReducer from "../prune_events_reducer";
import ReportKillReducer from "../report_kill_reducer";
import SendChatReducer from "../send_chat_reducer";
import SubmitScoreReducer from "../submit_score_reducer";
import UpdatePlayerReducer from "../update_player_reducer";

export type ClientConnectedParams = __Infer<typeof ClientConnectedReducer>;
export type ClientDisconnectedParams = __Infer<typeof ClientDisconnectedReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type PruneEventsParams = __Infer<typeof PruneEventsReducer>;
export type ReportKillParams = __Infer<typeof ReportKillReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SubmitScoreParams = __Infer<typeof SubmitScoreReducer>;
export type UpdatePlayerParams = __Infer<typeof UpdatePlayerReducer>;

